### ISSUE TITLE
Null-Safety?

### ISSUE THREAD

**Issue by d9media** [EdvaldoMartins/avatar_letter#11]
Hi and Thank you for the work on this package!

I was running `flutter outdated --mode=null-safety` to check which packages need upgrading to be compatible with null-safety and the command came back negative with avatar_letter.

Admittedly, I haven't really looked into the whole null-safety story much yet but are you aware of it and is the package compatible? Once I get a clear picture I can help out and port the code over. Just wondering whether this is something you had already looked into.

Cheers!

**Comment by srnunio** [comment]
Hello and thanks for the verification, the package still does not support null-safety more I will migrate soon and I am also open to contributions.

**Comment by d9media** [comment]
see #12

**Comment by d9media** [comment]
I created a pull request @EdvaldoMartins . Kindly feel free to merge it :)

**Comment by srnunio** [comment]
> I created a pull request @EdvaldoMartins . Kindly feel free to merge it :)

Just give me some time to validate.

**Comment by d9media** [comment]
Sure. 

There was a pub conflict with cupertino_icons which is why I removed the specific version. Also I added publish_to: none such that I was able to pull the package from my end. You don't need it obviously.
